version: "3.9"  # optional since v1.27.0
services:
    rabbit:
        image: "rabbitmq:management"
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - rabbit_data:/var/lib/rabbitmq
            - rabbit_log:/var/log/rabbitmq
        environment:
            - NODENAME=myrabbit@localhost
volumes:
    rabbit_data:
        external: true
    rabbit_log:
        external: true

